# Generated by Django 3.2.5 on 2021-12-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_materiainstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiainstance',
            name='due_back',
        ),
    ]
