# Generated by Django 3.2.5 on 2021-12-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211203_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comb_materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat1', models.CharField(max_length=100)),
                ('mat2', models.CharField(max_length=100)),
                ('mat3', models.CharField(max_length=100)),
                ('mat4', models.CharField(max_length=100)),
                ('mat5', models.CharField(max_length=100)),
                ('mat6', models.CharField(max_length=100)),
                ('mat7', models.CharField(max_length=100)),
                ('mat8', models.CharField(max_length=100)),
                ('mat9', models.CharField(max_length=100)),
                ('mat10', models.CharField(max_length=100)),
            ],
        ),
    ]
